---
# tasks file for test-jinja

- name: Render a template with "trim_blocks" set to False
  template:
    src: trim_blocks.j2
    dest: "{{output_dir}}/trim_blocks_false.templated"
    trim_blocks: False
  register: trim_blocks_false_result

- name: Get checksum of known good trim_blocks_false.expected
  stat:
    path: "{{role_path}}/files/trim_blocks_false.expected"
  register: trim_blocks_false_good

- name: Verify templated trim_blocks_false matches known good using checksum
  assert:
    that:
        - "trim_blocks_false_result.checksum == trim_blocks_false_good.stat.checksum"

- name: Render a template with "trim_blocks" set to True
  template:
    src: trim_blocks.j2
    dest: "{{output_dir}}/trim_blocks_true.templated"
    trim_blocks: True
  register: trim_blocks_true_result

- name: Get checksum of known good trim_blocks_true.expected
  stat:
    path: "{{role_path}}/files/trim_blocks_true.expected"
  register: trim_blocks_true_good

- name: Verify templated trim_blocks_true matches known good using checksum
  assert:
    that:
        - "trim_blocks_true_result.checksum == trim_blocks_true_good.stat.checksum"

# VERIFY lstrip_blocks

- name: Check support for lstrip_blocks in Jinja2
  shell: "{{ ansible_python.executable }} -c 'import jinja2; jinja2.defaults.LSTRIP_BLOCKS'"
  register: lstrip_block_support
  ignore_errors: True

- name: Render a template with "lstrip_blocks" set to False
  template:
    src: lstrip_blocks.j2
    dest: "{{output_dir}}/lstrip_blocks_false.templated"
    lstrip_blocks: False
  register: lstrip_blocks_false_result

- name: Get checksum of known good lstrip_blocks_false.expected
  stat:
    path: "{{role_path}}/files/lstrip_blocks_false.expected"
  register: lstrip_blocks_false_good

- name: Verify templated lstrip_blocks_false matches known good using checksum
  assert:
    that:
        - "lstrip_blocks_false_result.checksum == lstrip_blocks_false_good.stat.checksum"

- name: Render a template with "lstrip_blocks" set to True
  template:
    src: lstrip_blocks.j2
    dest: "{{output_dir}}/lstrip_blocks_true.templated"
    lstrip_blocks: True
  register: lstrip_blocks_true_result
  ignore_errors: True

- name: Verify exception is thrown if Jinja2 does not support lstrip_blocks but lstrip_blocks is used
  assert:
    that:
      - "lstrip_blocks_true_result.failed"
      - 'lstrip_blocks_true_result.msg is search(">=2.7")'
  when: "lstrip_block_support is failed"

- name: Get checksum of known good lstrip_blocks_true.expected
  stat:
    path: "{{role_path}}/files/lstrip_blocks_true.expected"
  register: lstrip_blocks_true_good
  when: "lstrip_block_support is successful"

- name: Verify templated lstrip_blocks_true matches known good using checksum
  assert:
    that:
        - "lstrip_blocks_true_result.checksum == lstrip_blocks_true_good.stat.checksum"
  when: "lstrip_block_support is successful"